"""initial schema

Revision ID: d61dc54a6d0d
Revises: 
Create Date: 2026-05-02 21:05:49.244880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd61dc54a6d0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('strava_access_token', sa.Text(), nullable=False),
    sa.Column('strava_refresh_token', sa.Text(), nullable=False),
    sa.Column('strava_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('recent_5k_secs', sa.Integer(), nullable=True),
    sa.Column('recent_10k_secs', sa.Integer(), nullable=True),
    sa.Column('available_days_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_injury', sa.Text(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('hr_zone1_max', sa.Integer(), nullable=True),
    sa.Column('hr_zone2_max', sa.Integer(), nullable=True),
    sa.Column('hr_zone3_max', sa.Integer(), nullable=True),
    sa.Column('hr_zone4_max', sa.Integer(), nullable=True),
    sa.Column('weekly_volume_goal_km', sa.Float(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_distance', sa.String(length=16), nullable=True),
    sa.Column('race_distance_m', sa.Float(), nullable=True),
    sa.Column('race_target_secs', sa.Integer(), nullable=True),
    sa.Column('next_planned_session_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_planned_session_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_planned_session_source', sa.String(length=16), nullable=True),
    sa.Column('next_planned_session_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_planned_session_run_id'], ['runs.id'], name='fk_users_next_planned_session_run_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_athlete_id'), 'users', ['athlete_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_invite_codes_created_by'), 'invite_codes', ['created_by'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('workout_type', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=16), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_secs', sa.Integer(), nullable=False),
    sa.Column('elapsed_secs', sa.Integer(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=False),
    sa.Column('elevation_high_m', sa.Float(), nullable=False),
    sa.Column('elevation_low_m', sa.Float(), nullable=False),
    sa.Column('avg_pace_min_km', sa.Float(), nullable=False),
    sa.Column('avg_speed_ms', sa.Float(), nullable=False),
    sa.Column('max_speed_ms', sa.Float(), nullable=False),
    sa.Column('pace_first_half_min', sa.Float(), nullable=False),
    sa.Column('pace_second_half_min', sa.Float(), nullable=False),
    sa.Column('pace_std_dev_min', sa.Float(), nullable=False),
    sa.Column('fastest_km_pace_min', sa.Float(), nullable=True),
    sa.Column('slowest_km_pace_min', sa.Float(), nullable=True),
    sa.Column('pace_splits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gap_min_km', sa.Float(), nullable=True),
    sa.Column('grade_avg_pct', sa.Float(), nullable=False),
    sa.Column('flat_distance_m', sa.Float(), nullable=False),
    sa.Column('uphill_distance_m', sa.Float(), nullable=False),
    sa.Column('downhill_distance_m', sa.Float(), nullable=False),
    sa.Column('grade_splits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('hr_zone1_secs', sa.Integer(), nullable=True),
    sa.Column('hr_zone2_secs', sa.Integer(), nullable=True),
    sa.Column('hr_zone3_secs', sa.Integer(), nullable=True),
    sa.Column('hr_zone4_secs', sa.Integer(), nullable=True),
    sa.Column('hr_zone5_secs', sa.Integer(), nullable=True),
    sa.Column('cardiac_drift_bpm', sa.Float(), nullable=True),
    sa.Column('aerobic_decoupling', sa.Float(), nullable=True),
    sa.Column('efficiency_factor', sa.Float(), nullable=True),
    sa.Column('hr_vs_pace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hr_zone_source', sa.String(length=32), nullable=True),
    sa.Column('cadence_avg', sa.Integer(), nullable=True),
    sa.Column('cadence_std_dev', sa.Float(), nullable=True),
    sa.Column('cadence_under170_pct', sa.Float(), nullable=True),
    sa.Column('cadence_splits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_time_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_distance_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_velocity_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_altitude_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_grade_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_hr_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream_cadence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claude_post_run_review', sa.Text(), nullable=True),
    sa.Column('claude_digest', sa.Text(), nullable=True),
    sa.Column('claude_next_session', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claude_load_rating', sa.String(length=16), nullable=True),
    sa.Column('claude_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_activity_id', name='uq_runs_strava_activity_id')
    )
    op.create_index(op.f('ix_runs_start_date'), 'runs', ['start_date'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_code'], ['invite_codes.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_start_date'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_invite_codes_created_by'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_athlete_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
